FROM alpine:latest

RUN apk update

RUN apk add mysql mysql-client && mkdir /var/lib/mysql && mkdir -p /run/mysqld && rm -rf /var/lib/apt/lists/* \
	&& rm -rf /var/lib/mysql && mkdir -p /var/lib/mysql /var/run/mysqld \
	&& chown -R mysql:mysql /var/lib/mysql /var/run/mysqld \
# ensure that /var/run/mysqld (used for socket and lock files) is writable regardless of the UID our mysqld instance ends up having at runtime
	&& chmod 1777 /var/run/mysqld /var/lib/mysql

RUN chown -R mysql /var/lib/mysql && \
    chgrp -R mysql /var/lib/mysql

# Initialize the data directory
RUN mysql_install_db --user=mysql --datadir=/var/lib/mysql 

# Configure MySQL to allow remote connections
RUN echo -e "[mysqld]\nbind-address = 0.0.0.0" > /etc/my.cnf

COPY ./init.sql /docker-entrypoint-initdb.d/

WORKDIR /docker-entrypoint-initdb.d

ENV MYSQL_ROOT_PASSWORD=O5Nz88BTPc6krzQ2gQuXJMOEroVKiY9po1LZSy1UQBk
ENV MYSQL_DATABASE=wordpress
ENV MYSQL_USER=wpuser
ENV MYSQL_PASSWORD=wpuser

EXPOSE 3306

LABEL version="1.0" \
    description="MySQL Database" \
    maintainer="Ethan Besson <contact@southlabs.fr>"

USER mysql    

CMD ["mysqld"]