FROM debian:bookworm-slim

# Update the system and install necessary packages
RUN apt-get update && apt-get install -y mariadb-server openssl

# Create necessary directories and set permissions
RUN mkdir -p /var/lib/mysql /var/run/mysqld && \
    chown -R mysql:mysql /var/lib/mysql /var/run/mysqld && \
    chmod 1777 /var/run/mysqld /var/lib/mysql

# Initialize the data directory
RUN mysql_install_db --user=mysql --datadir=/var/lib/mysql

COPY config/ /etc/mysql/

COPY ./init.sql /docker-entrypoint-initdb.d/

WORKDIR /docker-entrypoint-initdb.d

ENV MYSQL_ROOT_PASSWORD=O5Nz88BTPc6krzQ2gQuXJMOEroVKiY9po1LZSy1UQBk
ENV MYSQL_DATABASE=wordpress
ENV MYSQL_USER=wpuser
ENV MYSQL_PASSWORD=wpuser

EXPOSE 3306

LABEL version="1.0" \
    description="MySQL Database" \
    maintainer="Ethan Besson <contact@southlabs.fr>"

USER mysql

CMD ["mariadbd"]